### ISSUE TITLE
team communication should use soccer_vision_3d_msgs for obstacles

### ISSUE THREAD

**Issue by timonegk** [bit-bots/humanoid_league_misc#125]
Currently, the team communication still uses `humanoid_league_msgs/msg/ObstacleRelativeArray` for obstacles, but the ipm publishes obstacles as `soccer_vision_3d_msgs/msg/ObstacleArray`. I changed the interface already to avoid warnings but added a todo for more adaptions. Probably the vision is also affected and should be changed to use the `Robot` message type, such as `soccer_vision_3d_msgs/msg/RobotArray`.

**Comment by texhnolyze** [comment]
The current status after https://github.com/bit-bots/humanoid_league_misc/pull/127 is:
- team comm uses the `soccer_vision_3d_msgs/msg/RobotArray` messages from the vision
- these + other local messages/data are converted to protobuf
- upon receiving the protbuf data the robots are the converted to `humanoid_league_msgs/msg/ObstacleRelativeArray` for usage in the `TeamData` message.

As described in https://github.com/bit-bots/humanoid_league_msgs/issues/36, this should most likely be adjusted so that `TeamData` just contains `soccer_vision_3d_msgs` for obstacles/robots.
