### ISSUE TITLE
Use NUbots communication protocol

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_misc#6]
Rhoban implemented their own [communication protocol](https://github.com/Rhoban/hl_communication) based on Protobuf. We could use it instead of the mitecom. I'd suggest a fork of it. 

This is absolutely *not* urgent.

**Comment by TanjaSmiley** [comment]
Do we actually want to use the Rhoban communication protocol? Because in the rules from 2020 one has to decide to implement the mitecom protocol or the RoboCup protocol (https://github.com/RoboCup-Humanoid-TC/RobocupProtocol/blob/master/robocup.proto). The structure of the two protocols is not the same because in the Rhoban protocol more information is included leading to a more complex structure of the message.

Further the covariance is in the RoboCup protocol implemented as 3x3 matrix while in the Rhoban protocol it is  ( covar_x , covar_xy, covar_y).

**Comment by SammyRamone** [comment]
I thought that they wanted to change it to forced protobuf in the future. But at least it is not an urgend issue. @16stelter do you maybe know more?

**Comment by TanjaSmiley** [comment]
@SammyRamone There is a difference between the Protobuf Rhoban protocol mentioned by @NFiedler and the RoboCup Protobuf Protocol which is mentioned in the rules as it is a fork from the NuBots. So the question is not if we want to change to a Protobuf protocol, the question is which of the two Protobuf Protocols we want to use in the future.

**Comment by SammyRamone** [comment]
ahh, yeah I would say definitely the one from Rhoban, but maybe @NFiedler can give more input on this

**Comment by NFiedler** [comment]
I would prefer the Rhoban Protocol as it includes information like the Player role and stuff like that. Just because they transmit more information. But I am not sure, whether that protocol will be allowed in the future.

**Comment by SammyRamone** [comment]
Why should it not be allowed in the future? There was just the question of having either forced rhoban protocol or no specification if I remember correctly

**Comment by NFiedler** [comment]
I thought it was either NuBots Protocol or no specification because the RoboCup TC forked them. (https://github.com/RoboCup-Humanoid-TC/RobocupProtocol/blob/master/robocup.proto)

**Comment by SammyRamone** [comment]
Okay actually, when I said rhoban I meant the one proposed using protobuf. I now saw that the NUbots did some further work on it.
